# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# zonal_batch.py
# Created on: 2016-06-30 09:32:45.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
Wen_basin = "Wen_basin"
NARR = "D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR"
narrmon-a_221_20000801_0000_000_grb-var109-t0_flt = "D:\\OneDrive\\work\\GIS\\NARR\\2000\\Precip\\narrmon-a_221_20000801_0000_000.grb-var109-t0.flt"
wen_precip_0800 = "D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR\\wen_precip_0800"

# Process: Zonal Statistics as Table
arcpy.gp.ZonalStatisticsAsTable_sa(Wen_basin, "Id", narrmon-a_221_20000801_0000_000_grb-var109-t0_flt, wen_precip_0800, "DATA", "ALL")

# Process: Table to Table
arcpy.TableToTable_conversion(wen_precip_0800, NARR, "Wen_Precip_0800.dbf", "", "Id \"Id\" true true false 0 Long 0 0 ,First,#,D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR\\wen_precip_0800,Id,-1,-1;Count \"Count\" true true false 0 Long 0 0 ,First,#,D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR\\wen_precip_0800,Count,-1,-1;Area \"Area\" true true false 0 Double 0 0 ,First,#,D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR\\wen_precip_0800,Area,-1,-1;Min \"Min\" true true false 0 Double 0 0 ,First,#,D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR\\wen_precip_0800,Min,-1,-1;Max \"Max\" true true false 0 Double 0 0 ,First,#,D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR\\wen_precip_0800,Max,-1,-1;Range \"Range\" true true false 0 Double 0 0 ,First,#,D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR\\wen_precip_0800,Range,-1,-1;Mean \"Mean\" true true false 0 Double 0 0 ,First,#,D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR\\wen_precip_0800,Mean,-1,-1;Std \"Std\" true true false 0 Double 0 0 ,First,#,D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR\\wen_precip_0800,Std,-1,-1;Sum \"Sum\" true true false 0 Double 0 0 ,First,#,D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR\\wen_precip_0800,Sum,-1,-1", "")

