# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# zonal_batch_loop.py
# Created on: 2016-06-30 10:40:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
Wen_basin = "Wen_basin"
NARR = "D:\\OneDrive\\work\\research\\CHaMP\\CHaMP_data\\Wenatchee\\NARR"
Temp = "D:\\OneDrive\\work\\GIS\\NARR\\2002\\Temp"
Temp__2_ = "D:\\OneDrive\\work\\GIS\\NARR\\2002\\Temp"
narrmon-a_221_20020101_0000_000_grb-var74-t0_flt = "D:\\OneDrive\\work\\GIS\\NARR\\2002\\Temp\\narrmon-a_221_20020101_0000_000.grb-var74-t0.flt"
v_Name__dbf = "D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf"

# Process: Iterate Rasters
arcpy.IterateRasters_mb(Temp, "", "", "NOT_RECURSIVE")

# Process: Zonal Statistics as Table
arcpy.gp.ZonalStatisticsAsTable_sa(Wen_basin, "Id", narrmon-a_221_20020101_0000_000_grb-var74-t0_flt, v_Name__dbf, "DATA", "ALL")

# Process: Table to Table
arcpy.TableToTable_conversion(v_Name__dbf, Temp__2_, "%Name%_t.dbf", "", "Id \"Id\" true true false 0 Long 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Id,-1,-1;Count \"Count\" true true false 0 Long 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Count,-1,-1;Area \"Area\" true true false 0 Double 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Area,-1,-1;Min \"Min\" true true false 0 Long 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Min,-1,-1;Max \"Max\" true true false 0 Long 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Max,-1,-1;Range \"Range\" true true false 0 Long 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Range,-1,-1;Variety \"Variety\" true true false 0 Long 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Variety,-1,-1;Majority \"Majority\" true true false 0 Long 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Majority,-1,-1;Minority \"Minority\" true true false 0 Long 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Minority,-1,-1;Median \"Median\" true true false 0 Long 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Median,-1,-1;Mean \"Mean\" true true false 0 Double 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Mean,-1,-1;Std \"Std\" true true false 0 Double 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Std,-1,-1;Sum \"Sum\" true true false 0 Double 0 0 ,First,#,D:\\OneDrive\\work\\GIS\\NARR\\2002\\%Name%.dbf,Sum,-1,-1", "")

